version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    container_name: postgresClients
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres-clients
    ports:
      - '3002:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
